baseURL = 'https://yue-jenny.github.io'
languageCode = 'en-us'
title = 'Jenny blog'
theme = 'hugo-theme-stack'
publishDir = "docs"
enableEmoji  = "true"

[permalinks]
  post = '/:year/:month/:title/'

[Params]
	likerID = "yuemachi"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.8